spring:
  application:
    name: url_shortener
  datasource:
    url: jdbc:h2:mem:./url-shortener
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

code-generator:
  codeLength: 10
  numbers: false
  letters: true